Removing warnings, adding code styling.
SzFMV2022-Osz/AutomatedCar-A pull request #18
Opened 2022-09-30 08:59 UTC by Psichorex

Removed some analyser warnings.
Made some abstractions to collection types.
Added some generic code styling.

2022-10-01 12:08 UTC, erosd99 approved these changes
LGTM

2022-10-01 15:33 UTC, szeal12300 requested changes
see GlobalSuppressions.cs for comment

2022-10-01 15:33 UTC, szeal12300 commented on src/AutomatedCar/GlobalSuppressions.cs
> +[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "<Pending>", Scope = "member", Target = "~M:AutomatedCar.App.CreateWorld~Autom
I believe this could be applied globally, so it wouldn't be needed to add another line every time someone creates a public method

2022-10-05 07:44 UTC, erosd99 approved these changes
LGTM

2022-10-26 17:39 UTC, closed without merging